version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d marketplace_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    image: python:3.11-slim
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/marketplace_db
      SECRET_KEY: your-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      MERCADO_LIVRE_CLIENT_ID: 6987936494418444
      MERCADO_LIVRE_CLIENT_SECRET: puvG9Z7XBgICZg5yK3t0PAXAmnco18Tl
      MERCADO_LIVRE_REDIRECT_URI: https://adm.wolfx.com.br/api/mercado-livre/auth/callback
      ENVIRONMENT: production
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run build && cp -r dist/* /usr/share/nginx/html/ && nginx -g 'daemon off;'"
    depends_on:
      - backend

volumes:
  postgres_data_prod:
