version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: marketplace_db_prod
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d marketplace_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace_backend_prod
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/marketplace_db
      SECRET_KEY: your-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      MERCADO_LIVRE_CLIENT_ID: 6987936494418444
      MERCADO_LIVRE_CLIENT_SECRET: puvG9Z7XBgICZg5yK3t0PAXAmnco18Tl
      MERCADO_LIVRE_REDIRECT_URI: https://adm.wolfx.com.br/api/mercado-livre/auth/callback
      ENVIRONMENT: production
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: marketplace_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data_prod:

