"""add_mercado_livre_announcements_table

Revision ID: e13e0c31e3ab
Revises: 8eac912ac692
Create Date: 2025-09-20 15:52:49.818735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e13e0c31e3ab'
down_revision: Union[str, None] = '8eac912ac692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercado_livre_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ml_item_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_id', sa.String(length=10), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('sold_quantity', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('listing_type_id', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.String(length=100), nullable=True),
    sa.Column('domain_id', sa.String(length=100), nullable=True),
    sa.Column('catalog_listing', sa.Boolean(), nullable=True),
    sa.Column('catalog_product_id', sa.String(length=255), nullable=True),
    sa.Column('family_name', sa.String(length=500), nullable=True),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('user_product_id', sa.String(length=255), nullable=True),
    sa.Column('inventory_id', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('catalog_status', sa.String(length=50), nullable=True),
    sa.Column('catalog_visit_share', sa.String(length=50), nullable=True),
    sa.Column('catalog_competitors_sharing', sa.Integer(), nullable=True),
    sa.Column('catalog_price_to_win', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('full_data', sa.JSON(), nullable=True),
    sa.Column('sale_price_info', sa.JSON(), nullable=True),
    sa.Column('prices_info', sa.JSON(), nullable=True),
    sa.Column('catalog_position_info', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('pictures', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('ml_date_created', sa.DateTime(), nullable=True),
    sa.Column('ml_last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mercado_livre_announcements_id'), 'mercado_livre_announcements', ['id'], unique=False)
    op.create_index(op.f('ix_mercado_livre_announcements_ml_item_id'), 'mercado_livre_announcements', ['ml_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mercado_livre_announcements_ml_item_id'), table_name='mercado_livre_announcements')
    op.drop_index(op.f('ix_mercado_livre_announcements_id'), table_name='mercado_livre_announcements')
    op.drop_table('mercado_livre_announcements')
    # ### end Alembic commands ###