"""add_catalog_competitors_table

Revision ID: f1a2b3c4d5e6
Revises: e13e0c31e3ab
Create Date: 2024-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'e13e0c31e3ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('catalog_product_id', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('sold_quantity', sa.Integer(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.String(length=255), nullable=False),
    sa.Column('seller_nickname', sa.String(length=255), nullable=True),
    sa.Column('seller_reputation_level', sa.String(length=50), nullable=True),
    sa.Column('seller_power_status', sa.String(length=50), nullable=True),
    sa.Column('seller_transactions_total', sa.Integer(), nullable=True),
    sa.Column('shipping_mode', sa.String(length=50), nullable=True),
    sa.Column('shipping_logistic_type', sa.String(length=50), nullable=True),
    sa.Column('shipping_free', sa.Boolean(), nullable=True),
    sa.Column('shipping_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('listing_type_id', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('deal_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_date_created', sa.DateTime(), nullable=True),
    sa.Column('ml_last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_competitors_catalog_product_id'), 'catalog_competitors', ['catalog_product_id'], unique=False)
    op.create_index(op.f('ix_catalog_competitors_company_id'), 'catalog_competitors', ['company_id'], unique=False)
    op.create_index(op.f('ix_catalog_competitors_id'), 'catalog_competitors', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_competitors_item_id'), 'catalog_competitors', ['item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_competitors_item_id'), table_name='catalog_competitors')
    op.drop_index(op.f('ix_catalog_competitors_id'), table_name='catalog_competitors')
    op.drop_index(op.f('ix_catalog_competitors_company_id'), table_name='catalog_competitors')
    op.drop_index(op.f('ix_catalog_competitors_catalog_product_id'), table_name='catalog_competitors')
    op.drop_table('catalog_competitors')
    # ### end Alembic commands ###
