"""add product ads data table

Revision ID: i9j0k1l2m3n
Revises: h7i8j9k0l1m
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'i9j0k1l2m3n'
down_revision = 'h7i8j9k0l1m'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_ads_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('advertiser_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('has_discount', sa.Boolean(), nullable=True),
    sa.Column('catalog_listing', sa.Boolean(), nullable=True),
    sa.Column('logistic_type', sa.String(length=50), nullable=True),
    sa.Column('listing_type_id', sa.String(length=100), nullable=True),
    sa.Column('domain_id', sa.String(length=100), nullable=True),
    sa.Column('buy_box_winner', sa.Boolean(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('official_store_id', sa.Integer(), nullable=True),
    sa.Column('brand_value_id', sa.String(length=100), nullable=True),
    sa.Column('brand_value_name', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('current_level', sa.String(length=50), nullable=True),
    sa.Column('deferred_stock', sa.Boolean(), nullable=True),
    sa.Column('picture_id', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('prints', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('acos', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('organic_units_quantity', sa.Integer(), nullable=True),
    sa.Column('organic_units_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('organic_items_quantity', sa.Integer(), nullable=True),
    sa.Column('direct_items_quantity', sa.Integer(), nullable=True),
    sa.Column('direct_units_quantity', sa.Integer(), nullable=True),
    sa.Column('direct_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('indirect_items_quantity', sa.Integer(), nullable=True),
    sa.Column('indirect_units_quantity', sa.Integer(), nullable=True),
    sa.Column('indirect_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('advertising_items_quantity', sa.Integer(), nullable=True),
    sa.Column('units_quantity', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cvr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roas', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sov', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('impression_share', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('top_impression_share', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('lost_impression_share_by_budget', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('lost_impression_share_by_ad_rank', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('acos_benchmark', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('campaign_status', sa.String(length=50), nullable=True),
    sa.Column('campaign_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('campaign_acos_target', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('campaign_strategy', sa.String(length=50), nullable=True),
    sa.Column('full_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('campaign_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_date_created', sa.DateTime(), nullable=True),
    sa.Column('ml_last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_ads_data_id'), 'product_ads_data', ['id'], unique=False)
    op.create_index(op.f('ix_product_ads_data_item_id'), 'product_ads_data', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_ads_data_item_id'), table_name='product_ads_data')
    op.drop_index(op.f('ix_product_ads_data_id'), table_name='product_ads_data')
    op.drop_table('product_ads_data')
    # ### end Alembic commands ###
