"""add tacos column

Revision ID: j1k2l3m4n5o
Revises: i9j0k1l2m3n
Create Date: 2025-09-22 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'j1k2l3m4n5o'
down_revision = 'i9j0k1l2m3n'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_ads_data', sa.Column('tacos', sa.Numeric(precision=8, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_ads_data', 'tacos')
    # ### end Alembic commands ###
