"""add period_days to product_ads_data

Revision ID: l3m4n5o6p7q
Revises: j1k2l3m4n5o
Create Date: 2025-01-20 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'l3m4n5o6p7q'
down_revision = 'j1k2l3m4n5o'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_ads_data', sa.Column('period_days', sa.Integer(), nullable=True, default=15))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_ads_data', 'period_days')
    # ### end Alembic commands ###
