"""add data_period_start and data_period_end to product_ads_data

Revision ID: m4n5o6p7q8r
Revises: l3m4n5o6p7q
Create Date: 2025-01-20 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'm4n5o6p7q8r'
down_revision = 'l3m4n5o6p7q'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_ads_data', sa.Column('data_period_start', sa.DateTime(), nullable=True))
    op.add_column('product_ads_data', sa.Column('data_period_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_ads_data', 'data_period_end')
    op.drop_column('product_ads_data', 'data_period_start')
    # ### end Alembic commands ###
