"""add mercado_livre_orders table

Revision ID: n5o6p7q8r9s
Revises: m4n5o6p7q8r
Create Date: 2025-01-20 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'n5o6p7q8r9s'
down_revision = 'm4n5o6p7q8r'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercado_livre_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_detail', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency_id', sa.String(length=10), nullable=False),
    sa.Column('buyer_id', sa.String(length=50), nullable=False),
    sa.Column('buyer_nickname', sa.String(length=255), nullable=True),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('buyer_first_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_last_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('seller_nickname', sa.String(length=255), nullable=True),
    sa.Column('seller_email', sa.String(length=255), nullable=True),
    sa.Column('shipping_id', sa.String(length=50), nullable=True),
    sa.Column('shipping_status', sa.String(length=50), nullable=True),
    sa.Column('shipping_substatus', sa.String(length=50), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_method_id', sa.String(length=50), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_installments', sa.Integer(), nullable=True),
    sa.Column('feedback_sale_id', sa.String(length=50), nullable=True),
    sa.Column('feedback_sale_rating', sa.String(length=20), nullable=True),
    sa.Column('feedback_sale_fulfilled', sa.Boolean(), nullable=True),
    sa.Column('feedback_purchase_id', sa.String(length=50), nullable=True),
    sa.Column('feedback_purchase_rating', sa.String(length=20), nullable=True),
    sa.Column('feedback_purchase_fulfilled', sa.Boolean(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('order_items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('payments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('full_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_date_created', sa.DateTime(), nullable=True),
    sa.Column('ml_last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mercado_livre_orders_id'), 'mercado_livre_orders', ['id'], unique=False)
    op.create_index(op.f('ix_mercado_livre_orders_order_id'), 'mercado_livre_orders', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mercado_livre_orders_order_id'), table_name='mercado_livre_orders')
    op.drop_index(op.f('ix_mercado_livre_orders_id'), table_name='mercado_livre_orders')
    op.drop_table('mercado_livre_orders')
    # ### end Alembic commands ###

